#ifndef GEOMETRYSEARCHLIBRARY_GLOBAL_H
#define GEOMETRYSEARCHLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOMETRYSEARCHLIBRARY_LIBRARY)
#  define GEOMETRYSEARCHLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GEOMETRYSEARCHLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOMETRYSEARCHLIBRARY_GLOBAL_H
