#ifndef WIDGETLIBRARY_GLOBAL_H
#define WIDGETLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETLIBRARY_LIBRARY)
#  define WIDGETLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIDGETLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETLIBRARY_GLOBAL_H
